# Copyright 2019 Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: MIT-0
#
# Permission is hereby granted, free of charge, to any person obtaining a copy of this
# software and associated documentation files (the "Software"), to deal in the Software
# without restriction, including without limitation the rights to use, copy, modify,
# merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
# INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE
# SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Functionless URL Shortner

###################################################################################################
##   Template Parameters                                                                         ##
###################################################################################################
Parameters:
  AppName:
    Type: String
    Description: Name of application (no spaces). Value must be globally unique
    Default: shortener

###################################################################################################
##   Template Resources                                                                          ##
###################################################################################################
Resources:
  ##   API Gateway
  UrlShortenerAPI:
    Type: AWS::Serverless::Api
    Properties:
      Description: "URL Shortener API. Use API Key to access this service. See: https://github.com/bfansports/amazon-api-gateway-url-shortener.git"
      StageName: Prod
      EndpointConfiguration: EDGE
      TracingEnabled: true
      Auth:
        ApiKeyRequired: false
      MethodSettings:
        - HttpMethod: "*"
          ResourcePath: "/*"
          LoggingLevel: INFO
          DataTraceEnabled: true
          MetricsEnabled: true
          ThrottlingRateLimit: 2000
          ThrottlingBurstLimit: 1000
        - HttpMethod: "GET"
          ResourcePath: "/{linkId}"
          ThrottlingRateLimit: 10000
          ThrottlingBurstLimit: 4000
      DefinitionBody:
        'Fn::Transform':
          Name: 'AWS::Include'
          Parameters:
            Location: './api.yaml'

  ##   URL DynamoDB Table
  LinkTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: UrlShortenerLinks
      BillingMode: PAY_PER_REQUEST
      TimeToLiveSpecification:
        AttributeName: expiration
        Enabled: true
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: owner
          AttributeType: S
      GlobalSecondaryIndexes:
        - IndexName: OwnerIndex
          KeySchema:
            - AttributeName: owner
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  # API key definitions
  ShortenerApiKey:
    Type: AWS::ApiGateway::ApiKey
    DependsOn:
      - UrlShortenerAPI
    Properties:
      Name: Shortener API Key
      Description: API Key to be used by shortener users
      Enabled: 'true'
      StageKeys:
        - RestApiId:
            Ref: UrlShortenerAPI
          StageName: Prod
        - RestApiId:
            Ref: UrlShortenerAPI
          StageName: Stage

  # Linking of API keys to usage plans
  ShortenerUsagePlanKey:
    Type: "AWS::ApiGateway::UsagePlanKey"
    DependsOn:
      - UrlShortenerAPI
      - ShortenerApiKey
    Properties:
      KeyId:
        Ref: ShortenerApiKey
      KeyType: API_KEY
      UsagePlanId:
        Ref: ShortenerUsagePlan

  ShortenerUsagePlan:
    Type: AWS::ApiGateway::UsagePlan
    DependsOn:
      - UrlShortenerAPI
    Properties:
      UsagePlanName: bfan shortener Usage Plan
      Description: Usage plan for external providers pushing data to bfan
      ApiStages:
        - ApiId:
            Ref: UrlShortenerAPI
          Stage: Prod
        - ApiId:
            Ref: UrlShortenerAPI
          Stage: Stage
      Quota:
        Limit: 5000
        Period: MONTH
      Throttle:
        BurstLimit: 200
        RateLimit: 100

###################################################################################################
##   IAM Roles                                                                                   ##
###################################################################################################

  ##   Dynamo DB Read Role
  DDBReadRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service: "apigateway.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: DDBReadPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              Action:
              - dynamodb:GetItem
              - dynamodb:Scan
              - dynamodb:Query
              Effect: Allow
              Resource:
                - !GetAtt LinkTable.Arn
                - !Sub
                  - ${TableArn}/index/*
                  - {TableArn: !GetAtt LinkTable.Arn}

  ##   Dynamo DB Read/Write Role
  DDBCrudRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          -
            Effect: "Allow"
            Principal:
              Service: "apigateway.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Policies:
        - PolicyName: DDBCrudPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              Action:
              - dynamodb:DeleteItem
              - dynamodb:UpdateItem
              Effect: Allow
              Resource: !GetAtt LinkTable.Arn

  ##   Amplify Hosting Role
  AmplifyRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - amplify.amazonaws.com
            Action:
              - sts:AssumeRole
      Policies:
        - PolicyName: Amplify
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action: "amplify:*"
                Resource: "*"

## CloudWatchRole for aws gateway account
  Account:
    Type: 'AWS::ApiGateway::Account'
    Properties:
      CloudWatchRoleArn: !GetAtt CloudWatchRole.Arn

  CloudWatchRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - apigateway.amazonaws.com
            Action: 'sts:AssumeRole'
      Path: /
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs

###################################################################################################
##   Metrics outputs                                                                            ##
###################################################################################################

  APIGateway4xxAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: "URL Shortener API 4xx Alarm"
      AlarmDescription: "4xx monitor"
      MetricName: "4XXError"
      Namespace: "AWS/ApiGateway"
      Dimensions:
          - Name: "ApiName"
            Value: "URL Shortener API"
      Statistic: "Average"
      Period: 60
      EvaluationPeriods: 1
      Threshold: .01
      ComparisonOperator: "GreaterThanThreshold"
      AlarmActions:
        - Fn::ImportValue: EmailNotificationTopic

  APIGateway5xxAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: "URL Shortener API 5xx Alarm"
      AlarmDescription: "5xx monitor"
      MetricName: "5XXError"
      Namespace: "AWS/ApiGateway"
      Dimensions:
          - Name: "ApiName"
            Value: "URL Shortener API"
      Statistic: "Average"
      Period: 60
      EvaluationPeriods: 1
      Threshold: .01
      ComparisonOperator: "GreaterThanThreshold"
      AlarmActions:
        - Fn::ImportValue: EmailNotificationTopic

  APIGatewayLatencyAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: "URL Shortener API Latency Alarm"
      AlarmDescription: "Latency monitor"
      MetricName: "Latency"
      Namespace: "AWS/ApiGateway"
      Dimensions:
          - Name: "ApiName"
            Value: "URL Shortener API"
      ExtendedStatistic: "p99"
      Period: 300
      EvaluationPeriods: 1
      Threshold: 75
      ComparisonOperator: "GreaterThanThreshold"
      AlarmActions:
        - Fn::ImportValue: EmailNotificationTopic

  DDB5xxAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: "URL Shortener DDB 5xx Alarm"
      AlarmDescription: "System monitor"
      MetricName: "SystemErrors"
      Namespace: "AWS/DynamoDB"
      Dimensions:
          - Name: "TableName"
            Value: !Ref LinkTable
      Statistic: "Average"
      Period: 60
      EvaluationPeriods: 1
      Threshold: .01
      ComparisonOperator: "GreaterThanThreshold"
      AlarmActions:
        - Fn::ImportValue: EmailNotificationTopic

  DDB4xxAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: "URL Shortener DDB 4xx Alarm"
      AlarmDescription: "User monitor"
      MetricName: "UserErrors"
      Namespace: "AWS/DynamoDB"
      Dimensions:
          - Name: "TableName"
            Value: !Ref LinkTable
      Statistic: "Average"
      Period: 60
      EvaluationPeriods: 1
      Threshold: .10
      ComparisonOperator: "GreaterThanThreshold"
      AlarmActions:
        - Fn::ImportValue: EmailNotificationTopic
